### ISSUE TITLE
真的变快了吗？

### ISSUE THREAD

**Issue by yygutn** [trycatchx/RocketXPlugin#10]
我对壳工程加了一行代码，测试加这个插件or不加这个插件，都是20s结束

**Comment by trycatchx** [comment]
效果展现的柱状图是基于 一个 3W 个类文件（不包含第三方库），68个module 的工程的效果展现。
如果使用 demo 做速度测试，其中每一个 module 仅只有一两个 class，并没有对比意义（demo 只是为了测试解决依赖的替换和插件正常运行） 


**原生编译**：对于一个模块A的改动，任何依赖了 A 的模块都会重新编译（如果A 是 comm 模块基本整个项目都要编）
**插件加速编译**：对于一个模块A的改动，只编译 A 和 app 模块

综上在插件能做到只编译改动模块。原生编译则不行。

所以是否变快很容易得出结论了。

**Comment by yygutn** [comment]
好的吧，对于includeBuild是否支持呢

**Comment by trycatchx** [comment]
@yygutn  目前还没做 includeBuild 混合构建的测试。还没支持上来。

**Comment by trycatchx** [comment]
@yygutn 如果你这边有这边的经验和环境，欢迎提 PR

**Comment by yygutn** [comment]
@trycatchx 最近在试用的时候，经常遇到这个问题： Type XXX is defined multiple times， clean build后就好了

**Comment by trycatchx** [comment]
@yygutn 使用最新的1.0.6试试。

**Comment by trycatchx** [comment]
@yygutn  这种引起类重复的原因是：项目使用了自定义的 transforms ，然后在没gradle 没有增量的情况 每调用 outputProvider.deleteAll() ，导致 依赖变化时候，module 换成 aar ，module 缓存没剔除 ，又多了一份一模一样的 aar 。

建议在debug 阶段如果使用了 transform 通过以下代码禁止，如果没影响的话。（内部目前禁用了 arouter 神策 等插件）：

```
 RocketX {
        // 禁用可禁用的 transform ，速度更快
        transFormList = ["sensorsAnalyticsAutoTrack","..xx"]
    }
```

**Comment by yygutn** [comment]
谢谢大佬，真实勤劳的小蜜蜂 @trycatchx

**Comment by zxhandroid** [comment]
> 

有些不能禁用的话，怎么处理呢，./gradlew clean 后，还是会报重复类的错误
