### ISSUE TITLE
能对比一下它和instant run的优缺点么？

### ISSUE THREAD

**Issue by inflexible-simple** [trycatchx/RocketXPlugin#11]

**Comment by trycatchx** [comment]
Android Studio 3.5 Instant Run 已经被遗弃了，取而代之的是 Apply Changes。Apply Changes 在实际体验中经常变灰色没法使用（部分修改不支持），希望谷歌官方能逐步完善。

至于和 RocketXPlugin 的对比, 我认为速度是可以叠加，两者没有冲突。RocketXPlugin 只是把 module 换成 aar 不参与编译。所以 Apply Changes 拿到的就是 一个 app module 和 多个 aar 的一个 project 。

**Comment by trycatchx** [comment]
@inflexible-simple  但是目前还没有支持 Apply Changes  的测试，毕竟 Apply Changes  实际使用还是存在问题。
