### ISSUE TITLE
是不是意味着对增量编译是没有提升效果的？

### ISSUE THREAD

**Issue by realchenzhi** [trycatchx/RocketXPlugin#12]
我理解RocketX其实是跟增量编译一个实现原理

**Comment by trycatchx** [comment]
@realchenzhi  可能大家对增量的理解不太一样。

我理解的编译增量原理是热修复，通过新增的代码打出补丁包，通过 adb 推送到当前的 app 进行热更新。维护成本，适配各Android 版本 AGP 版本 兼容性问题多。（就像隔壁的 fastdex 好久没有维护了 ）

rockext 方向不一样，具体看我 blog 介绍。维护兼容性成本低，稳定性强。

**Comment by trycatchx** [comment]
@realchenzhi 你说的这个 增量编译 是 gradle 本身的增量 还是类似 fastdex 开源库的增量？

 fastdex 编译增量原理是热修复，通过新增的代码打出补丁包，通过 adb 推送到当前的 app 进行热更新。维护成本，适配各Android 版本 AGP 版本 兼容性问题多。（目前好像好久没有维护了 ）

对于 gradle 的增量 ：rockext 在其基础上提速度。
对于 fastdex ：rockext 提速思路方向不一样，具体看我 [blog](https://www.jianshu.com/p/59b95b5a7fab) 介绍。所以也造就兼容性稳定性强。
