### ISSUE TITLE
本地maven服务的路径在哪里

### ISSUE THREAD

**Issue by GHyejb** [trycatchx/RocketXPlugin#13]
你好，我想问一下本地maven服务里面保存的aar在哪里路径啊

**Comment by trycatchx** [comment]
![image](https://user-images.githubusercontent.com/6050250/145779106-e0369c19-b3d2-44b5-acf5-fc528ea9109e.png)
目前直接使用 Flat 的方式引入依赖速度快于 LocalMaven。

**Comment by GHyejb** [comment]
收到，谢谢

**Comment by trycatchx** [comment]
@GHyejb  最新在做一个不同项目体量速度提升统计，有时间可以反馈一下哦：

- 项目体量描述
- 不同模块代码修改速度提升描述

你的反馈是我们持续优化提升的动力。
