### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by realchenzhi** [trycatchx/RocketXPlugin#15]
![image](https://user-images.githubusercontent.com/75719863/145806108-3280267e-c7e1-4ad6-9263-3a6a6f27fcba.png)

第二次clean后build就会报错了。
另外我的使用RocktX的方式，在build.gradle(app)下添加了
```
apply plugin: 'com.rocketx'
```
然后开启小火箭插件才有效（.gradle下有缓存），文档好像没有写到这个apply

**Comment by realchenzhi** [comment]
再 run 还是一样报错

**Comment by realchenzhi** [comment]
![image](https://user-images.githubusercontent.com/75719863/145811203-e6ef5828-56a2-4b2c-83f7-0b51d499b315.png)
报错太多了，有点奇怪。 agp 4.0.1  gradle 6.1.1

**Comment by trycatchx** [comment]
> ![image](https://user-images.githubusercontent.com/75719863/145806108-3280267e-c7e1-4ad6-9263-3a6a6f27fcba.png)
> 
> 第二次clean后build就会报错了。 另外我的使用RocktX的方式，在build.gradle(app)下添加了
> 
> ```
> apply plugin: 'com.rocketx'
> ```
> 
> 然后开启小火箭插件才有效（.gradle下有缓存），文档好像没有写到这个apply

是的需要加入 apply plugin: 'com.rocketx' ，后面我再文档上补一下。

**Comment by trycatchx** [comment]
> ![image](https://user-images.githubusercontent.com/75719863/145811203-e6ef5828-56a2-4b2c-83f7-0b51d499b315.png) 报错太多了，有点奇怪。 agp 4.0.1 gradle 6.1.1

voice 的 build.gradle 方便看一下吗？（关闭 rockectx 是可以编译过去的吗?）

**Comment by trycatchx** [comment]
@realchenzhi 看样子好像是 资源链接的问题？gradle sync ![image](https://user-images.githubusercontent.com/6050250/145814944-cd7cb537-c70d-43b3-8ad1-599f5cbc7789.png)一下再编译

**Comment by realchenzhi** [comment]
> 
gradle sync 还是会有问题，看起来只有app模块对其他模块的引用资源会报错。

**Comment by trycatchx** [comment]
@realchenzhi 我在 demo 中，使用 app module 引用 projectC 的 资源目前没有发现问题。

**Comment by trycatchx** [comment]
@realchenzhi  你看下能找到导致这个问题的具体原因不。
![image](https://user-images.githubusercontent.com/6050250/146001816-9d5f603d-bfed-4611-9de6-59b9652e0f50.png)
