### ISSUE TITLE
第一次全量编译正常，后面会导致依赖错误

### ISSUE THREAD

**Issue by GHyejb** [trycatchx/RocketXPlugin#19]
你好，问题如上
只有第一次可以正常运行，后面就包同样的问题
agp 4.0.2
gradle 6.1.1

Cannot change dependencies of dependency configuration ':library:imageloader:compileOnly' after it has been included in dependency resolution.

**Comment by trycatchx** [comment]
@GHyejb  同 issue #18 ，目前已经找到问题，在修复中。

**Comment by GHyejb** [comment]
好的，刚看到那个issue，谢谢

**Comment by trycatchx** [comment]
使用 classpath 'io.github.trycatchx:rocketx:1.0.12' 解决以上问题
