### ISSUE TITLE
请教，这种编译运行报错怎么解决

### ISSUE THREAD

**Issue by jiqianwen** [trycatchx/RocketXPlugin#21]
![QQ截图20211224095745](https://user-images.githubusercontent.com/26268908/147306422-01893ded-cee0-4ac1-a836-83e57ca433ad.png)
![QQ截图20211224095757](https://user-images.githubusercontent.com/26268908/147306430-3c04cef9-6265-44bc-bc0b-e68f6b14f248.png)

**Comment by trycatchx** [comment]
@jiqianwen  使用 classpath 'io.github.trycatchx:rocketx:1.0.13' ，  详情 [gradle7.0](https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation)

**Comment by trycatchx** [comment]
@jiqianwen  task  一些内部变量需要使用 @Internal 进行标识。不过好像 gradle 7.X 又取消了这个限制？
