### ISSUE TITLE
每次都重新生成aar

### ISSUE THREAD

**Issue by GHyejb** [trycatchx/RocketXPlugin#23]
还是上次的问题，没有修改任何代码，大部分模块都重新打包了
我打算源码引用一下这个插件，本地调试看看，请问如何操作？
代码下载的熬本地，只需要将红色部分提取出来就可以吗？

![image](https://user-images.githubusercontent.com/45551976/147328558-b0c21f57-87cb-4c21-ba8b-f4e5051a27ee.png)
![image](https://user-images.githubusercontent.com/45551976/147328766-3d96698e-3a09-4c28-868e-d48bcb5d125d.png)

**Comment by trycatchx** [comment]
是的，直接复制粘贴过去。把 claspath 去掉就可以了。感谢分析问题

**Comment by GHyejb** [comment]
好的，谢谢，我先自己看看

**Comment by trycatchx** [comment]
@GHyejb  你可以查阅 getChangeModuleMap.kt  中的 getChangeModuleMap 方法看下每次 输出 的改动模块 是否有值。

如果你没有做改动，而输出有值，说明是有问题。就会导致 uploadLocalmaven 触发。

如果输出正常，可以查看 AarFlatLocalMaven.kt 代码流程是有问题

**Comment by GHyejb** [comment]
好的，正在引入源码

**Comment by trycatchx** [comment]
@GHyejb 嗯嗯，如果发现有问题欢迎 提 PR

**Comment by GHyejb** [comment]
你好，这个是什么问题啊，编译的时候
![image](https://user-images.githubusercontent.com/45551976/147337791-75326a4e-3601-4af9-9f73-d7e70fbd52f1.png)

**Comment by GHyejb** [comment]
Unresolved reference: maven

**Comment by trycatchx** [comment]
配置一下 使用 flat 為 localmaven
```
   RocketX {
        openLog = true
        localMaven = false
    }
```

**Comment by trycatchx** [comment]
@GHyejb  目前有两种方式 localMaven ，
1、使用flat 直接copy 到指定缓存目录，依赖的时候只需指定 文件路径的 aar 就可以
2、使用 真正的 localmaven ，多了一些pom.xml 解析操作 ，较慢（目前建议使用第一种 flat）

**Comment by trycatchx** [comment]
@GHyejb  具体源码 就是在 FlatTask 这个 task

**Comment by GHyejb** [comment]
![image](https://user-images.githubusercontent.com/45551976/147338807-9d29111e-577a-4b10-8d1d-123ee31c650d.png)
还是有问题，目前在app的gradle中加了这两个东西，项目根目录下面引入buildSrc

**Comment by trycatchx** [comment]
@GHyejb 加在android  闭包内。文档我更新一下。

**Comment by GHyejb** [comment]
还是报错
![image](https://user-images.githubusercontent.com/45551976/147339874-b6979b2f-bbca-4ffb-b6d4-287acce32306.png)

**Comment by trycatchx** [comment]
@GHyejb   gradle sync 一下再编译

**Comment by trycatchx** [comment]
@GHyejb  这里配置了 false ，理论上是跑不进去的：

![image](https://user-images.githubusercontent.com/6050250/147341164-0dab4bda-9744-4f65-9688-ba903576f4f0.png)

**Comment by GHyejb** [comment]
还是这样

**Comment by GHyejb** [comment]
那我吧代码注释看看

**Comment by trycatchx** [comment]
@trycatchx  你可以帮忙 debug 一下   if (mRocketXBean?.localMaven == true)  这个条件语句 为什么是 true ？

**Comment by GHyejb** [comment]
> @GHyejb 你可以查阅 ChangeModuleUtils.kt 中的 getChangeModuleMap 方法看下每次 输出 的改动模块 是否有值。
> 
> 如果你没有做改动，而输出有值，说明是有问题。就会导致 uploadLocalmaven 触发。
> 
> 如果输出正常，可以查看 AarFlatLocalMaven.kt 代码流程是有问题

刚刚不知道为什么编译不过去，既然代码不从那边走，那我直接注释了，现在成功了，我后面按照你给的提示调试一下
谢谢！
![image](https://user-images.githubusercontent.com/45551976/147342086-89a6e382-fe66-46ad-892c-63dd70c447f6.png)

**Comment by trycatchx** [comment]
看截图生成缓存位置，走的是falt，那么刚刚那个条件语句理论是 false ，这么奇怪？

**Comment by GHyejb** [comment]
感觉是我本地的环境导致没法编译

**Comment by trycatchx** [comment]
好的，那你帮忙排查是否有多次 uploadLoalMaven 的生成的原因？
