### ISSUE TITLE
gradle最低版本

### ISSUE THREAD

**Issue by ZShiDong** [trycatchx/RocketXPlugin#25]
目前最低兼容6.1.1 可否兼容至5.4.1 项目有点大 升级起来可能会有问题 如果工作量很大 可贡献一下微薄之力 虽然本人很菜 但可以花时间学习一下

**Comment by trycatchx** [comment]
很不幸的是我们团队目前还没有足够的精力来兼容 gradle  较低的版本，而且较低的版本会慢慢被淘汰，以及没有较好的编译性能。

这一块如果你需要适配可以先行尝试，当然遇到的问题我们这边会尽力去帮助你。

**Comment by ZShiDong** [comment]
好的,谢谢
