### ISSUE TITLE
org.gradle.configureondemand=true，会导致编译失败

### ISSUE THREAD

**Issue by po1xiao** [trycatchx/RocketXPlugin#26]
gradle.properties中配置org.gradle.configureondemand=true，会导致编译失败，排查了半天才发现是这么配置引起的。如果这个配置是必须不能配置成true的，建议在ReadMe中添加说明，不然会对有这个配置的用户造成一些困扰。

AGP：7.0.4， Gradle：7.0.2

rocketx:1.0.17

**Comment by trycatchx** [comment]
@po1xiao  好的感谢提示，我会在 readme 补充一下。

**Comment by haizhiyun** [comment]
org.gradle.configureondemand=true 这个问题好解吗，在mac m1 pro/max 上都会出现
