### ISSUE TITLE
最新版本1.0.17在gradle上同一个手机每次运行都需要3-5分钟

### ISSUE THREAD

**Issue by lhj1079947827** [trycatchx/RocketXPlugin#27]
以前的版本在同一个手机上运行不会出现这种现象，但是更新到最新版本1.0.17后每次运行都是3-5分钟左右，不知道最新版本更新了什么

**Comment by lhj1079947827** [comment]
[
![image](https://user-images.githubusercontent.com/20966610/148003977-6f2f6e24-0b69-402a-bc07-9e937c7792aa.png)
](url)

**Comment by trycatchx** [comment]
@lhj1079947827 请问之前是什么版本？

**Comment by lhj1079947827** [comment]
1.0.14版本

**Comment by trycatchx** [comment]
有一个修改的点是：excludeTransForms 的位置变了。你可能要重新更改一下：

excludeTransForms： 阶段可以禁用的 transform ，速度更快（可通过build 的 log 搜索关键字 transFormList 查看自己项目引用了哪些 transform，并手动配置在 gradle.properties 文件下）
# 使用空格间隔开
excludeTransForms = com.alibaba.arouter

**Comment by lhj1079947827** [comment]
我看看吧

**Comment by trycatchx** [comment]
我看到你的截图 AMPplugin重新运行了。

**Comment by lhj1079947827** [comment]
主要耗时的还是compileDebugKotlin这个

**Comment by trycatchx** [comment]
@lhj1079947827  重新接入 rockectx 会重新编译插件的源码，会导致整个编译流程的增量会失效。你可以尝试多运行几次看看速度

**Comment by lhj1079947827** [comment]
但是不可能每次都是重新编译插件的源码吧，我这里是每次都是运行都是走编译插件的源码了，感觉这个增量编译没起作用。

**Comment by trycatchx** [comment]
@lhj1079947827 主要是接入的第一次会比较慢，后面就正常了。

**Comment by trycatchx** [comment]
> 但是不可能每次都是重新编译插件的源码吧，我这里是每次都是运行都是走编译插件的源码了，感觉这个增量编译没起作用。

每次都是 compileDebugKotlin 耗时吗？kotlin 编译优化有加入 譬如：


```
org.gradle.daemon=true
kotlin.incremental=true
kotlin.incremental.java=true
kotlin.incremental.js=true
kotlin.caching.enabled=true

# 开启kotlin并行编译
kotlin.parallel.tasks.in.project=true
# 优化kapt
# 并行运行kapt1.2.60版本以上支持
kapt.use.worker.api=true
# 增量编译 kapt1.3.30版本以上支持
kapt.incremental.apt=true
# positive value will enable caching
# use the same value as the number of modules that use kapt
# 如果您连续运行许多 Gradle 任务，则缓存注释处理器的类加载器有助于 kapt 执行得更快
kapt.classloaders.cache.size=5
# kapt avoiding 如果用kapt依赖的内容没有变化，会完全重用编译内容，省掉`app:kaptGenerateStubsDebugKotlin`的时间
kapt.include.compile.classpath=false
```

**Comment by lhj1079947827** [comment]
是的，刚才就是想问问是不是加入了这个原因，我有加入这个

**Comment by trycatchx** [comment]
1.0.14-10.17 没有做编译速度相关的动作，主要是修复配置 和 兼容agp7. 0

**Comment by trycatchx** [comment]
但是每次 app module 感觉都没有做原有增量编译，应该是有问题，你可以尝试不接入rockectx ，查看 app module 是否一直都没有增量？可能需要你帮忙排查原因。

**Comment by trycatchx** [comment]
@lhj1079947827  请问有新的进展吗？
