### ISSUE TITLE
插件如何编译

### ISSUE THREAD

**Issue by GHyejb** [trycatchx/RocketXPlugin#28]
* mac debug 插件命令 ：export GRADLE_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"
 在源码看到这个，想debug一下，应该如何操作

**Comment by trycatchx** [comment]
@GHyejb  选中 assembledebug ，标记断点，点击 Debug（昆虫按钮），这个方式较为简单无需配置任何命令，你试试。

**Comment by GHyejb** [comment]
可以了，谢谢
