### ISSUE TITLE
最新源码编译出现这个问题

### ISSUE THREAD

**Issue by GHyejb** [trycatchx/RocketXPlugin#30]
![image](https://user-images.githubusercontent.com/45551976/148191440-c05528cd-129d-4fb4-808d-fbc689fc5bda.png)
复现的规律暂时没有找到，这个问题你们出现过吗

**Comment by GHyejb** [comment]
#18 复现情况有点像这个，第一次编译可以，第二次就错了，但是有时候再试几次又能成功

**Comment by trycatchx** [comment]
@GHyejb  网络问题。

**Comment by GHyejb** [comment]
感觉不太像啊，第一次编译可以，立即再编译一次，出现这个问题
关闭插件项目能正常编译了

**Comment by trycatchx** [comment]
你可以尝试使用 1.0.1 版本。RC 是候选版本。然后你可以用手机的热点试试，看这个异常信息是网络原因

![image](https://user-images.githubusercontent.com/6050250/148197636-c51e885e-b9d6-4ee0-b394-a7aefa323701.png)

**Comment by GHyejb** [comment]
好的，我试试，谢谢

**Comment by trycatchx** [comment]
@GHyejb 好的，如果有出现其他的问题请反馈，我们这边会尽力帮忙排查。

**Comment by GHyejb** [comment]
找到问题了，我这里用了两个版本，结果插件在打印依赖关系的时候冲突导致的

**Comment by trycatchx** [comment]
好的，很高兴听到这个消息

**Comment by GHyejb** [comment]
插件最新进展--好消息
目前是使用源码引入插件的，和目前的代码做了一些兼容，终于能用了，目前只开了8个子模块，编译速度比之前会快一些，但是不是很多，可能是源码引入的模块比较少，导致效果不是特别大，后面会增加子模块去验证。
下面的遇到的几个问题和解决方案
1、由于我们的项目有个插件会在编译的时后在每个module生成一个文件夹，导致这个问题 #23 ，关闭了项目里的插件就好了
2、目前过滤了build文件夹，但是如果子module是独立的仓库，每次都会扫描进这个文件夹，这里面是不是可以不用扫描，里面的文件还挺多的，我尝试了过滤这个文件夹也能正常运行
![image](https://user-images.githubusercontent.com/45551976/148339628-4d5b0fc2-b81e-42dd-82b6-707c40d921e9.png)
3、AJXTransform这个无法被excludeTransForms识别和禁止编译，目前我是把项目里面AJXTransform关闭了
4、有时候mergeDebugJavaResource耗时较长

**Comment by trycatchx** [comment]
@GHyejb  很高兴听到这个消息
问题2：是的，理论只是扫描源码部分即可。
问题3 ：gradle.properties 配置  excludeTransForms ajx
![image](https://user-images.githubusercontent.com/6050250/148341860-bfe3e366-6dbe-4f6b-ae8f-9c5654f6c466.png)
问题4：这块 rockectx 没做任何动作，可能需要你排查一下是否有资源文件变动？

**Comment by GHyejb** [comment]
问题三那样试过，还是会编译，而且build中transFormList没有输出，感觉是rocketx没有检测到使用了ajx，等后面有时间再排查一下这里

**Comment by trycatchx** [comment]
@GHyejb 好的，请问方便贴出引入 ajx 方式？方便我们这边在工程中尝试复现出问题并解决它。

**Comment by GHyejb** [comment]
classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.10'
根目录的 build.gradle

**Comment by trycatchx** [comment]
```
apply plugin: 'android-aspectjx'
//或者这样也可以
apply plugin: 'com.hujiang.android-aspectjx'
```
app module  build.gradle  是否添加以上插件？

**Comment by GHyejb** [comment]
app中添加了
apply plugin: 'android-aspectjx'

**Comment by trycatchx** [comment]
@GHyejb  好的，感谢。

**Comment by trycatchx** [comment]
@GHyejb 你使用的AGP 版本是多少？我在 demo 进行 ajx 测试是可以 exclude 成功

**Comment by GHyejb** [comment]
4.0.2
6.1.1
你的transFormList有输出吗？

**Comment by trycatchx** [comment]
@GHyejb 
我在 gradle.propertity 添加 excludeTransForms = ajx ，transFormList 没有输出，并且 task 没有被执行。

**Comment by GHyejb** [comment]
换成我的agp版本ajx就没法被过滤是吗？agp版本导致的吗

**Comment by trycatchx** [comment]
@GHyejb  
agp 6.0+的 transform 字段：为 _transform ,
agp 6.0 以下的是 transform 

所以 6.0 以下目前插件会 exclude 不成功。但是你是 6.1.1 理论没有问题。这个就令我很苦恼

**Comment by GHyejb** [comment]
源码调的话我应该在哪些地方打断点，我这边试试看

**Comment by trycatchx** [comment]
查看 BaseExtension.kt 代码里面的变量即可

**Comment by GHyejb** [comment]
好的，我看看

**Comment by trycatchx** [comment]
这个我关了，如果后期有出现新的问题。你再提 issue
