### ISSUE TITLE
请问为什么禁止 release 使用加速插件?

### ISSUE THREAD

**Issue by shenzhen2017** [trycatchx/RocketXPlugin#32]
我看插件中对release做了直接返回，为什么不能在release中使用呢？

**Comment by trycatchx** [comment]
@shenzhen2017  目前插件开放了 excludeTransForms 的功能，极大程度加快编译，同时丧失在 debug 环境可以忽略的功能。因此不建议在 release 环境使用（毕竟 release 环境打包次数也相对较少）

综上： 建议在 debug （频繁改动）使用插件，获得最大速度收益
