### ISSUE TITLE
底层模块的方法若变动，而调用该方法的上层模块未变动即AAR依赖，则可能会出现编译成功但运行失败情况

### ISSUE THREAD

**Issue by xiaoxiaozero** [trycatchx/RocketXPlugin#33]
底层模块的方法若变动，而调用该方法的上层模块未变动即AAR依赖，则可能会出现编译成功但运行失败情况
比如模块A依赖模块B，且调用模块B的的test方法。
此时我们只将模块B的test方法命名为test1，正常Gradle打包时会编译模块A以及模块B，因此模块A会编译失败导致打包失败。而使用rocketx的话，模块A由于未改动，即此时模块A是AAR依赖，不会去编译，因此会编译成功但运行失败(找不到模块B的test方法)。

**Comment by trycatchx** [comment]
@xiaoxiaozero   重复 [issue29](https://github.com/trycatchx/RocketXPlugin/issues/29)
