### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by Ganzkiller** [trycatchx/RocketXPlugin#34]
module A引用了module B的类，全量编译后的下次编译会报错，无法找到类，这个偶现
Android resource linking failed，无法找到资源，也是其余module下的资源，必现
AGP:4.0.1
gradle:6.1.1

![image](https://user-images.githubusercontent.com/18693754/153408410-29e7c4e6-f861-4c96-a711-7eb2b038f781.png)

**Comment by trycatchx** [comment]
@Ganzkiller 如果没有问题，我即将关闭本 issue ，
如果问题解决了欢迎提 PR ，如果问题仍然存在请再提issue。
