### ISSUE TITLE
有人碰到AndroidX适配问题了吗？

### ISSUE THREAD

**Issue by GHyejb** [trycatchx/RocketXPlugin#4]
The given artifact contains a string literal with a package reference 'android.support.design.widget' that cannot be safely rewritten. Libraries using reflection such as annotation processors need to be updated manually to add support for androidx.

**Comment by GHyejb** [comment]
> Failed to transform '/Users/macos/.gradle/caches/modules-2/files-2.1/com.android.tools.build/bundletool/0.13.2/bb629ece022e5aa20cff66517e728c89f9667721/bundletool-0.13.2.jar' using Jetifier. Reason: The given artifact contains a string literal with a package reference 'android.support.design.widget' that cannot be safely rewritten. Libraries using reflection such as annotation processors need to be updated manually to add support for androidx.. (Run with --stacktrace for more details.)

**Comment by louis-lzt** [comment]
我们项目中也用了AndroidX，并没有出现这个兼容的问题，你这个像是项目中有旧的代码引起的对AndroidX的冲突

**Comment by louis-lzt** [comment]
> 给定的工件包含一个字符串文字，其中包含无法安全重写的包引用“android.support.design.widget”。需要手动更新使用反射（例如注释处理器）的库以添加对 androidx 的支持。

能否给出详细的环境信息，agp 版本，是否使用了transform ？ 能贴出相应的代码吗？

**Comment by trycatchx** [comment]
目前 rockext 没有对 androidX 做任何动作，你的问题可以查阅  [issuetracker](https://issuetracker.google.com/issues/118658603#comment5) ，[stackoverflower](https://stackoverflow.com/questions/54207116/android-annotation-processors-need-to-be-updated-manually-to-add-support-for-an) , 确认项目本身能运行通过。如与rockext 相关，可提 issue ，并告诉详细信息。

**Comment by GHyejb** [comment]
稍等，我一会再试试
