### ISSUE TITLE
manifest合并报错

### ISSUE THREAD

**Issue by 972223177** [trycatchx/RocketXPlugin#41]
头两次编译正常，第三次必定会出现合并报错，
![image](https://user-images.githubusercontent.com/28978619/155646910-6408bac1-99e0-47ff-867d-2c15149a2be3.png)
这两个activity是第三方的，这里replace覆盖了样式和screenOrientation。
![image](https://user-images.githubusercontent.com/28978619/155647066-f21130cb-e25b-4a03-b546-78e3d04bbec9.png)
但其实已经声明过了replace了。

**Comment by trycatchx** [comment]
@972223177  你好，如果这两个` <activity/>` 申明是在子 `module`（非 `app module`） 中的，你可以尝试把这两个迁移到 `app module` 的 `androidManifest.xml`,再进行编译。 因为 子`module` 打成 `aar` 之后 `replace` 属性会丢失

**Comment by 972223177** [comment]
诚聘网络兼职工资日结!还不错~
详情请登陆招聘网站http://brorx.cn/?;

**Comment by 972223177** [comment]
> @972223177 你好，如果这两个` <activity/>` 申明是在子 `module`（非 `app module`） 中的，你可以尝试把这两个迁移到 `app module` 的 `androidManifest.xml`,再进行编译。 因为 子`module` 打成 `aar` 之后 `replace` 属性会丢失

谢谢！有效！但是请问有其他办法解决这样的问题吗，我们希望appModule尽量保持干净

**Comment by trycatchx** [comment]
@972223177 你查看readme ，有一个excludeModule属性，直接强制指定模块不打成aar (速度可能有略微影响，具体看模块大小)。 目前这一个问题，还没有想到较完美的方案，需要不断探索。
如果你有好的想法，欢迎给我们提pr
