### ISSUE TITLE
clone项目编译后，AppExtension类导入不进来

### ISSUE THREAD

**Issue by cornflower10** [trycatchx/RocketXPlugin#46]
![image](https://user-images.githubusercontent.com/8315609/156926480-178fd667-baf4-4f29-aa2d-55cb714ac524.png)

**Comment by trycatchx** [comment]
@cornflower10  sync 一下，依赖包没有拉到?

**Comment by louis-lzt** [comment]
sync 一下， 如果失败gradle 版本号能提供一下？

**Comment by cornflower10** [comment]
> @cornflower10 sync 一下，依赖包没有拉到?

同步也不行
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by cornflower10** [comment]
> @cornflower10 sync 一下，依赖包没有拉到?
同步也不行
![image](https://user-images.githubusercontent.com/8315609/156983819-729ddc8d-c461-4c20-a4e5-dad2f7dec4f9.png)
![image](https://user-images.githubusercontent.com/8315609/156983858-d8507691-9ffe-46ca-95c4-8adc27bbd88c.png)

**Comment by louis-lzt** [comment]
distributionUrl 你改成 https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip  然后sync 一下 试试；如果你想用Gradle版本：7.2，Android Studio/AGP 版本修复为：7.1.1

**Comment by louis-lzt** [comment]
distributionUrl 你改成 https://services.gradle.org/distributions/gradle-7.0.2-bin.zip  然后sync 一下 试试；
如果你想用Gradle版本：7.2，Android Studio/AGP 版本修改为：7.1.1

**Comment by cornflower10** [comment]
> distributionUrl 你改成 https://services.gradle.org/distributions/gradle-7.0.2-bin.zip 然后sync 一下 试试； 如果你想用Gradle版本：7.2，Android Studio/AGP 版本修改为：7.1.1

目前已经修改distributionUrl 你改成 https://services.gradle.org/distributions/gradle-7.0.2-bin.zip 然后sync 一下，还是导不进来，这个AppExtension类是获取的App模块下的参数，是不是需要其他依赖

**Comment by trycatchx** [comment]
@cornflower10 你好 把 as 升级到最新版本 按照以下配置规则：
根目录build.gradle
    classpath 'com.android.tools.build:gradle:7.1.1'
buildsrc 的 build.gradle
    implementation 'com.android.tools.build:gradle:7.1.1'
根目录/gradle :
distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip

**Comment by trycatchx** [comment]
> > distributionUrl 你改成 https://services.gradle.org/distributions/gradle-7.0.2-bin.zip 然后sync 一下 试试； 如果你想用Gradle版本：7.2，Android Studio/AGP 版本修改为：7.1.1
> 
> 目前已经修改distributionUrl 你改成 https://services.gradle.org/distributions/gradle-7.0.2-bin.zip 然后sync 一下，还是导不进来，这个AppExtension类是获取的App模块下的参数，是不是需要其他依赖

AppExtension 这个类是在 implementation 'com.android.tools.build:gradle:7.1.1' 这个插件里面的。

**Comment by cornflower10** [comment]
> > > distributionUrl 你改成 https://services.gradle.org/distributions/gradle-7.0.2-bin.zip 然后sync 一下 试试； 如果你想用Gradle版本：7.2，Android Studio/AGP 版本修改为：7.1.1
> > 
> > 
> > 目前已经修改distributionUrl 你改成 https://services.gradle.org/distributions/gradle-7.0.2-bin.zip 然后sync 一下，还是导不进来，这个AppExtension类是获取的App模块下的参数，是不是需要其他依赖
> 
> AppExtension 这个类是在 implementation 'com.android.tools.build:gradle:7.1.1' 这个插件里面的。

昨天晚上搞了好久一直很奇怪，今天早上把androidStudio删了，安装最新版本就好了
