### ISSUE TITLE
demo 里面没有找到

### ISSUE THREAD

**Issue by Newwaygo** [trycatchx/RocketXPlugin#5]
![image](https://user-images.githubusercontent.com/8821153/144161410-15dd81db-f121-4927-b63c-cd6bc8419f18.png)

demo 里面没有找打 zPlugin
如果使用了 arouter ，请使用 zPlugin 文件夹中的 本地 arouter 进行替换（查看demo 如何替换），速度更快（后期研究是否有更好的办法解决这个问题）

**Comment by trycatchx** [comment]
有的 在这里 ：
![image](https://user-images.githubusercontent.com/6050250/144161927-12003c9c-d044-4387-b212-e669b761d1b0.png)


替换方式：
```
//        classpath 'com.alibaba:arouter-register:1.0.2'
        classpath fileTree(dir: './zPlugin',
                include: ['*.jar'])
    }
```
