### ISSUE TITLE
mavenPublish使用project.name可能导致重复

### ISSUE THREAD

**Issue by QuincyJiang** [trycatchx/RocketXPlugin#6]
比如module结构是
push
    :service
     :impl
log
    :service
    :impl

RocketX只会发布两个aar，一个servce.aar一个impl.aar
log模块的会覆盖push

**Comment by JustAClamber** [comment]
> 比如module结构是 push :service :impl log :service :impl
> 
> RocketX只会发布两个aar，一个servce.aar一个impl.aar log模块的会覆盖push
现在确实会有这个问题，后续会考虑使用project的path进行替换。

**Comment by QuincyJiang** [comment]
#7

**Comment by JustAClamber** [comment]
> Bugfix pr: #7
刚刚我已提交了修复的代码，同时修复了一个依赖冲突的问题
`if (isAndroid) {
            project.dependencies.add(configName, "${projectPath.getMavenGroupId()}:${projectName}:1.0@aar")
        } else {
            project.dependencies.add(configName, "${projectPath.getMavenGroupId()}:${projectName}:1.0@jar")
        }`

**Comment by trycatchx** [comment]
使用 flat 作为 本地仓库，目前也已经做调整。目前采用 project.getPath 替换 project.name。

举例：
log
:service

push
:service
生成两个 aar 名字为 ：log-service.aar, push-service.aar  (目前没发用 冒号：，gradle 解析依赖会导致冲突，所以目前使用 - 先行解决)

[commit](https://github.com/trycatchx/RocketXPlugin/commit/5a77506437b57460d2664c10061ab6fd3be66369)

@QuincyJiang
